// Switch to the default database defined in .env.example
db = db.getSiblingDB('blocklist');

print("Initializing Blocklist Library with default community lists...");

var rawLists = [
    // ADVERTISING
    { name: "AdAway", url: "https://adaway.org/hosts.txt", category: "advertising", description: "Mobile-focused ad blocking. Very low false positives. Android-oriented.", recommended: true, aggressiveness: 2, domain_count: 6423 },
    { name: "AdGuard Base Filter", url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt", category: "advertising", description: "AdGuard's base filter. Official AdGuard ad blocking rules.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "Admiral Anti-Adblock", url: "https://v.firebog.net/hosts/Admiral.txt", category: "advertising", description: "Admiral anti-adblock domains. Blocks anti-adblock detection scripts.", recommended: true, aggressiveness: 3, domain_count: 1753 },
    { name: "Anudeep Adservers", url: "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt", category: "advertising", description: "Curated ad server list. Well-maintained with good community support.", recommended: true, aggressiveness: 3, domain_count: 37532 },
    { name: "EasyList Firebog", url: "https://v.firebog.net/hosts/Easylist.txt", category: "advertising", description: "Classic EasyList converted to hosts. Broad ad blocking coverage.", recommended: true, aggressiveness: 3, domain_count: 49845 },
    { name: "Hagezi Pop-Up Ads", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/popupads.txt", category: "advertising", description: "Annoying and malicious pop-ups. Targets aggressive advertising.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "Ad-Wars", url: "https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts", category: "advertising", description: "Chinese ad blocking. Excellent Chinese ad network coverage.", recommended: false, aggressiveness: 3, domain_count: 1632 },
    { name: "AdGuard DNS Filter", url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt", category: "advertising", description: "AdGuard DNS-specific filter. Optimized for DNS-level blocking.", recommended: false, aggressiveness: 3, domain_count: 6423 },
    { name: "AdGuard Mobile Ads", url: "https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardMobileAds.txt", category: "advertising", description: "Mobile-specific ad blocking. Targets mobile app and browser ads.", recommended: false, aggressiveness: 3, domain_count: 893 },
    { name: "BlockListProject Ads", url: "https://blocklistproject.github.io/Lists/ads.txt", category: "advertising", description: "Curated advertising domains. Part of the comprehensive BlockList Project.", recommended: false, aggressiveness: 3, domain_count: 146119 },
    { name: "EasyList Official", url: "https://easylist.to/easylist/easylist.txt", category: "advertising", description: "Official EasyList (Adblock syntax). For AdGuard Home/uBlock Origin.", recommended: false, aggressiveness: 3, domain_count: 4242 },
    { name: "FadeMind UncheckyAds", url: "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts", category: "advertising", description: "Unchecky project ad domains. Blocks software bundling ads.", recommended: false, aggressiveness: 2, domain_count: 9 },
    { name: "Lightswitch Tracking", url: "https://raw.githubusercontent.com/lightswitch05/hosts/master/docs/lists/tracking-aggressive-extended.txt", category: "advertising", description: "Extended tracking and ads. Aggressive approach to ad/tracking blocking.", recommended: false, aggressiveness: 4, domain_count: 168038 },
    { name: "TheGreatWall", url: "https://raw.githubusercontent.com/Sekhan/TheGreatWall/master/TheGreatWall.txt", category: "advertising", description: "Comprehensive Chinese ad/tracking blocking. Great for Chinese content.", recommended: false, aggressiveness: 4, domain_count: 130 },
    { name: "hostsVN", url: "https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts", category: "advertising", description: "Vietnamese ad blocking. Good Asian ad network coverage.", recommended: false, aggressiveness: 3, domain_count: 17204 },

    // COMPREHENSIVE
    { name: "Hagezi Multi Normal", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/multi.txt", category: "comprehensive", description: "Relaxed/balanced blocking (~241K domains). Shouldn't cause restrictions. Great for environments without admin support.", recommended: true, aggressiveness: 2, domain_count: 253562 },
    { name: "Hagezi Pro", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.txt", category: "comprehensive", description: "Balanced protection. Blocks error trackers (Bugsnag, Crashlytics, Sentry). Good balance of blocking and usability.", recommended: true, aggressiveness: 3, domain_count: 314511 },
    { name: "Hagezi Pro++", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/pro.plus.txt", category: "comprehensive", description: "Aggressive blocking (~370K domains). More aggressive than Pro, blocks error trackers. Good for experienced users.", recommended: true, aggressiveness: 4, domain_count: 0 },
    { name: "Hagezi Ultimate", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/ultimate.txt", category: "comprehensive", description: "Maximum protection (~500K domains). Blocks ads, tracking, telemetry, phishing, malware, scam, cryptojacking. May restrict some app functionality.", recommended: true, aggressiveness: 5, domain_count: 0 },
    { name: "OISD Small", url: "https://small.oisd.nl", category: "comprehensive", description: "Curated all-in-one list. Updates every 20 mins. Excellent false positive handling. Less aggressive than Big.", recommended: true, aggressiveness: 2, domain_count: 0 },
    { name: "StevenBlack Unified", url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts", category: "comprehensive", description: "Classic unified hosts file. Combines multiple reputable sources. Well-maintained and regularly updated.", recommended: true, aggressiveness: 3, domain_count: 74152 },
    { name: "1Hosts Lite", url: "https://badmojr.github.io/1Hosts/Lite/hosts.txt", category: "comprehensive", description: "Lightweight but effective. Focuses on ads and trackers with minimal false positives.", recommended: false, aggressiveness: 2, domain_count: 183968 },
    { name: "Bongochong Combined", url: "https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/newhosts-final.hosts", category: "comprehensive", description: "Combined privacy blocklist. Aggregates multiple sources into one list.", recommended: false, aggressiveness: 4, domain_count: 209397 },
    { name: "GoodbyeAds", url: "https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt", category: "comprehensive", description: "Comprehensive ad blocking. Popular in Asian regions, good mobile coverage.", recommended: false, aggressiveness: 3, domain_count: 239576 },
    { name: "Hagezi Light", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/light.txt", category: "comprehensive", description: "Lightweight protection. Minimal blocking, very low false positives. Good starting point.", recommended: false, aggressiveness: 1, domain_count: 95123 },
    { name: "MVPS Hosts", url: "https://winhelp2002.mvps.org/hosts.txt", category: "comprehensive", description: "Long-standing hosts file. Conservative, reliable, good for beginners.", recommended: false, aggressiveness: 2, domain_count: 8482 },
    { name: "NoTracking", url: "https://raw.githubusercontent.com/notracking/hosts-blocklists/master/hostnames.txt", category: "comprehensive", description: "Privacy-focused blocking. Blocks tracking domains while maintaining site functionality.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "Pyenb Comprehensive", url: "https://raw.githubusercontent.com/Pyenb/Pi-hole-blocklist/main/blocklist.txt", category: "comprehensive", description: "Large combined blocklist (~2.4M domains). Updated daily. Very comprehensive coverage.", recommended: false, aggressiveness: 5, domain_count: 0 },
    { name: "SomeoneWhoCares", url: "https://someonewhocares.org/hosts/hosts", category: "comprehensive", description: "Classic, well-maintained hosts file. Conservative blocking, very reliable.", recommended: false, aggressiveness: 2, domain_count: 11849 },
    { name: "StevenBlack Extended", url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts", category: "comprehensive", description: "Unified + fakenews + gambling + porn + social media blocking. Comprehensive protection plus content filtering.", recommended: false, aggressiveness: 4, domain_count: 160137 },

    // MALICIOUS
    { name: "CERT Poland", url: "https://hole.cert.pl/domains/domains_hosts.txt", category: "malicious", description: "Polish CERT threat intelligence. Updated daily. Government-backed security data.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "CyberHost Malware", url: "https://lists.cyberhost.uk/malware.txt", category: "malicious", description: "UK-based malware blocklist. Updated multiple times daily. Cross-checked against Cloudflare Top Domains.", recommended: true, aggressiveness: 3, domain_count: 19982 },
    { name: "Hagezi Fake", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/fake.txt", category: "malicious", description: "Fake stores, streaming scams, fraudulent sites. Protects against online fraud.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "Hagezi TIF Full", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/hosts/tif.txt", category: "malicious", description: "Complete Threat Intelligence Feeds (~647K domains). Aggregates 30+ threat intel sources. Very comprehensive security.", recommended: true, aggressiveness: 4, domain_count: 0 },
    { name: "Hagezi TIF Medium", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.medium.txt", category: "malicious", description: "Medium-sized threat intelligence. Good balance of coverage and resource usage.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "Jarelllama Scam", url: "https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/adblock/scams.txt", category: "malicious", description: "Automated scam detection (~468K domains). Daily updates. Excellent scam coverage.", recommended: true, aggressiveness: 4, domain_count: 0 },
    { name: "Phishing Army Extended", url: "https://phishing.army/download/phishing_army_blocklist_extended.txt", category: "malicious", description: "Extended phishing protection. Aggregates PhishTank, OpenPhish, CERT feeds. Updates 6-hourly.", recommended: true, aggressiveness: 3, domain_count: 151884 },
    { name: "Stalkerware Indicators", url: "https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts", category: "malicious", description: "Spyware/stalkerware domains. Used by Quad9. Protects against surveillance software.", recommended: true, aggressiveness: 3, domain_count: 906 },
    { name: "URLhaus Malware", url: "https://urlhaus.abuse.ch/downloads/hostfile/", category: "malicious", description: "abuse.ch malware URLs. Updates every 5 minutes. Excellent for active threats.", recommended: true, aggressiveness: 3, domain_count: 525 },
    { name: "BlockListProject Malware", url: "https://blocklistproject.github.io/Lists/malware.txt", category: "malicious", description: "Curated malware domains. Well-maintained project with multiple formats.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "BlockListProject Phishing", url: "https://blocklistproject.github.io/Lists/phishing.txt", category: "malicious", description: "Curated phishing domains. Part of the BlockList Project suite.", recommended: false, aggressiveness: 3, domain_count: 187835 },
    { name: "BlockListProject Ransomware", url: "https://blocklistproject.github.io/Lists/ransomware.txt", category: "malicious", description: "Ransomware C2 and distribution domains. Essential for ransomware protection.", recommended: false, aggressiveness: 3, domain_count: 1348 },
    { name: "Botvrij IOC", url: "https://www.botvrij.eu/data/ioclist.hostname", category: "malicious", description: "Botnet indicators of compromise. Dutch security research.", recommended: false, aggressiveness: 3, domain_count: 8 },
    { name: "Curbengh Phishing Filter", url: "https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt", category: "malicious", description: "Curated phishing protection. Regular updates, low false positives.", recommended: false, aggressiveness: 3, domain_count: 21388 },
    { name: "Curbengh URLhaus Filter", url: "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-hosts.txt", category: "malicious", description: "URLhaus data in hosts format. Alternative format for abuse.ch data.", recommended: false, aggressiveness: 3, domain_count: 7887 },
    { name: "DandelionSprout Anti-Malware", url: "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt", category: "malicious", description: "Actively maintained malware list. Good community support and updates.", recommended: false, aggressiveness: 3, domain_count: 14477 },
    { name: "Hagezi TIF Mini", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/tif.mini.txt", category: "malicious", description: "Lightweight threat intelligence. Essential threats only, minimal resource usage.", recommended: false, aggressiveness: 2, domain_count: 0 },
    { name: "Phishing Army Basic", url: "https://phishing.army/download/phishing_army_blocklist.txt", category: "malicious", description: "Basic phishing protection. Core phishing domains, lower false positive risk.", recommended: false, aggressiveness: 2, domain_count: 150820 },
    { name: "Prigent Malware", url: "https://v.firebog.net/hosts/Prigent-Malware.txt", category: "malicious", description: "French university malware list. Academic research-backed.", recommended: false, aggressiveness: 3, domain_count: 245257 },
    { name: "RPiList Malware", url: "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware", category: "malicious", description: "German Pi-hole community malware list. Regularly updated.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "Spam404", url: "https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt", category: "malicious", description: "Scam and spam domains. Community-maintained, good coverage.", recommended: false, aggressiveness: 3, domain_count: 8052 },
    { name: "StopForumSpam Toxic", url: "https://www.stopforumspam.com/downloads/toxic_domains_whole.txt", category: "malicious", description: "Toxic spam domains. Data from forum spam reports.", recommended: false, aggressiveness: 3, domain_count: 65743 },
    { name: "Threat-Intel Latest", url: "https://raw.githubusercontent.com/davidonzo/Threat-Intel/master/lists/latestdomains.piHole.txt", category: "malicious", description: "Latest threat intelligence domains. Fresh threat data.", recommended: false, aggressiveness: 4, domain_count: 131 },

    // NSFW
    { name: "BlockListProject Porn", url: "https://blocklistproject.github.io/Lists/porn.txt", category: "nsfw", description: "Curated pornography blocking. Part of BlockList Project suite.", recommended: true, aggressiveness: 3, domain_count: 0 },
    { name: "OISD NSFW", url: "https://nsfw.oisd.nl", category: "nsfw", description: "Comprehensive adult content blocking. Same quality as OISD main list. Very thorough.", recommended: true, aggressiveness: 4, domain_count: 0 },
    { name: "StevenBlack Porn", url: "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts", category: "nsfw", description: "StevenBlack base + porn blocking. Trusted source combination.", recommended: true, aggressiveness: 3, domain_count: 149234 },
    { name: "Anti-Porn HOSTS", url: "https://raw.githubusercontent.com/4skinSkywalker/Anti-Porn-HOSTS-File/master/HOSTS.txt", category: "nsfw", description: "Anti-pornography hosts file. Community-maintained.", recommended: false, aggressiveness: 3, domain_count: 89718 },
    { name: "BlockListProject Drugs", url: "https://blocklistproject.github.io/Lists/drugs.txt", category: "nsfw", description: "Drug-related site blocking. Online pharmacies, drug markets.", recommended: false, aggressiveness: 4, domain_count: 25233 },
    { name: "BlockListProject Gambling", url: "https://blocklistproject.github.io/Lists/gambling.txt", category: "nsfw", description: "Gambling site blocking. Online casinos, betting sites.", recommended: false, aggressiveness: 4, domain_count: 2457 },
    { name: "BlockListProject Piracy", url: "https://blocklistproject.github.io/Lists/piracy.txt", category: "nsfw", description: "Piracy site blocking. Torrent sites, illegal streaming.", recommended: false, aggressiveness: 4, domain_count: 2127 },
    { name: "BlockListProject Torrent", url: "https://blocklistproject.github.io/Lists/torrent.txt", category: "nsfw", description: "Torrent site blocking. BitTorrent trackers and sites.", recommended: false, aggressiveness: 4, domain_count: 2601 },
    { name: "ChadMayfield Porn All", url: "https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_all.list", category: "nsfw", description: "Comprehensive porn list. Very large coverage.", recommended: false, aggressiveness: 4, domain_count: 0 },
    { name: "ChadMayfield Porn Top1M", url: "https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list", category: "nsfw", description: "Top 1M porn domains. More focused than full list.", recommended: false, aggressiveness: 3, domain_count: 11731 },
    { name: "ColumnDeeply Porn", url: "https://raw.githubusercontent.com/columndeeply/hosts/main/hosts00", category: "nsfw", description: "Large unified porn blocklist (10M+ domains). Split into multiple files (hosts00-05).", recommended: false, aggressiveness: 5, domain_count: 0 },
    { name: "MHHakim Porn", url: "https://raw.githubusercontent.com/mhhakim/pihole-blocklist/master/porn.txt", category: "nsfw", description: "Curated porn blocklist. Good balance of coverage and size.", recommended: false, aggressiveness: 3, domain_count: 236605 },
    { name: "OISD NSFW Small", url: "https://nsfw-small.oisd.nl", category: "nsfw", description: "Lighter NSFW blocking. For adblockers with size limitations.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "Sinfonietta Porn", url: "https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts", category: "nsfw", description: "Pornography hosts file. Good general coverage.", recommended: false, aggressiveness: 3, domain_count: 60035 },
    { name: "Tiuxo Porn", url: "https://raw.githubusercontent.com/tiuxo/hosts/master/porn", category: "nsfw", description: "Additional porn blocking. Complements other lists.", recommended: false, aggressiveness: 3, domain_count: 367 },

    // SUSPICIOUS
    { name: "Hagezi DoH/VPN/Proxy Bypass", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/doh-vpn-proxy-bypass.txt", category: "suspicious", description: "Prevents DNS filter bypass. Blocks DoH, VPN, proxy services that bypass filtering.", recommended: true, aggressiveness: 4, domain_count: 0 },
    { name: "NoCoin Hosts", url: "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt", category: "suspicious", description: "Browser cryptomining blocking. Prevents in-browser mining.", recommended: true, aggressiveness: 3, domain_count: 312 },
    { name: "Polish KAD Hosts", url: "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt", category: "suspicious", description: "Fraud, scam, suspicious domains. Polish research team.", recommended: true, aggressiveness: 3, domain_count: 41973 },
    { name: "Prigent Crypto", url: "https://v.firebog.net/hosts/Prigent-Crypto.txt", category: "suspicious", description: "Cryptominer blocking. French university research-backed.", recommended: true, aggressiveness: 3, domain_count: 11190 },
    { name: "BlockListProject Abuse", url: "https://blocklistproject.github.io/Lists/abuse.txt", category: "suspicious", description: "Abuse-related domains. Sites associated with abuse/harassment.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "BlockListProject Crypto", url: "https://blocklistproject.github.io/Lists/crypto.txt", category: "suspicious", description: "Cryptocurrency-related blocking. Crypto mining and scam domains.", recommended: false, aggressiveness: 3, domain_count: 23625 },
    { name: "BlockListProject Fraud", url: "https://blocklistproject.github.io/Lists/fraud.txt", category: "suspicious", description: "Fraud domain blocking. Known fraudulent websites.", recommended: false, aggressiveness: 3, domain_count: 193319 },
    { name: "BlockListProject Redirect", url: "https://blocklistproject.github.io/Lists/redirect.txt", category: "suspicious", description: "Malicious redirects. URL shorteners and redirectors used maliciously.", recommended: false, aggressiveness: 3, domain_count: 105514 },
    { name: "BlockListProject Scam", url: "https://blocklistproject.github.io/Lists/scam.txt", category: "suspicious", description: "Scam domain blocking. Online scam websites.", recommended: false, aggressiveness: 3, domain_count: 1239 },
    { name: "FadeMind Spam", url: "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts", category: "suspicious", description: "Spam domain blocking. Reduces spam and unwanted content.", recommended: false, aggressiveness: 2, domain_count: 55 },
    { name: "Hagezi DynDNS", url: "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklists@latest/adblock/dyndns.txt", category: "suspicious", description: "DynDNS services. Blocks DynDNS often abused for phishing.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "Matomo Referrer Spam", url: "https://raw.githubusercontent.com/matomo-org/referrer-spam-list/master/spammers.txt", category: "suspicious", description: "Referrer spam blocking. From Matomo analytics project.", recommended: false, aggressiveness: 2, domain_count: 2206 },
    { name: "RPiList Crypto", url: "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto", category: "suspicious", description: "German Pi-hole crypto list. Cryptomining and crypto scam blocking.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "RPiList Spam Mail", url: "https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails", category: "suspicious", description: "Spam email domains. Blocks known spam sources.", recommended: false, aggressiveness: 2, domain_count: 0 },
    { name: "SNAFU", url: "https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt", category: "suspicious", description: "Suspicious domains list. Community-maintained suspicious activity blocking.", recommended: false, aggressiveness: 3, domain_count: 65446 },
    { name: "W3KBL", url: "https://v.firebog.net/hosts/static/w3kbl.txt", category: "suspicious", description: "Web3 and crypto scam blocking. Static list of known bad actors.", recommended: false, aggressiveness: 3, domain_count: 350 },

    // TRACKING
    { name: "EasyPrivacy Firebog", url: "https://v.firebog.net/hosts/Easyprivacy.txt", category: "tracking", description: "Classic EasyPrivacy in hosts format. Comprehensive tracking protection.", recommended: true, aggressiveness: 3, domain_count: 42174 },
    { name: "Frogeye First-Party Trackers", url: "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt", category: "tracking", description: "CNAME cloaked trackers (~31K hostnames). Blocks sophisticated first-party tracking.", recommended: true, aggressiveness: 4, domain_count: 31851 },
    { name: "Hagezi Amazon", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.amazon.txt", category: "tracking", description: "Amazon/Fire TV telemetry. For Echo, Fire TV, and other Amazon devices.", recommended: true, aggressiveness: 3, domain_count: 624 },
    { name: "Hagezi Roku", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.roku.txt", category: "tracking", description: "Roku telemetry and home screen ads. Essential for Roku privacy.", recommended: true, aggressiveness: 3, domain_count: 157 },
    { name: "Hagezi Windows Telemetry", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.winoffice.txt", category: "tracking", description: "Windows/Office telemetry. Replaces abandoned WindowsSpyBlocker.", recommended: true, aggressiveness: 3, domain_count: 2212 },
    { name: "NextDNS CNAME Cloaking", url: "https://raw.githubusercontent.com/nextdns/cname-cloaking-blocklist/master/domains", category: "tracking", description: "NextDNS CNAME cloaking blocklist. Targets DNS-based tracking evasion.", recommended: true, aggressiveness: 4, domain_count: 33 },
    { name: "Perflyst Android Tracking", url: "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt", category: "tracking", description: "Mobile device trackers. Essential for Android privacy.", recommended: true, aggressiveness: 3, domain_count: 79 },
    { name: "Perflyst SmartTV", url: "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt", category: "tracking", description: "Samsung, LG, Vizio, Fire TV, Roku telemetry and ads. Essential for smart TV privacy.", recommended: true, aggressiveness: 3, domain_count: 240 },
    { name: "AdGuard Tracking Protection", url: "https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt", category: "tracking", description: "AdGuard tracking protection filter. Official AdGuard tracking rules.", recommended: false, aggressiveness: 3, domain_count: 0 },
    { name: "BlockListProject Facebook", url: "https://blocklistproject.github.io/Lists/facebook.txt", category: "tracking", description: "Facebook/Meta blocking. Blocks Facebook services network-wide.", recommended: false, aggressiveness: 5, domain_count: 22278 },
    { name: "BlockListProject TikTok", url: "https://blocklistproject.github.io/Lists/tiktok.txt", category: "tracking", description: "TikTok blocking. Blocks TikTok services network-wide.", recommended: false, aggressiveness: 5, domain_count: 3684 },
    { name: "BlockListProject Tracking", url: "https://blocklistproject.github.io/Lists/tracking.txt", category: "tracking", description: "Curated tracking domains. Part of the BlockList Project suite.", recommended: false, aggressiveness: 3, domain_count: 14964 },
    { name: "BlockListProject YouTube", url: "https://blocklistproject.github.io/Lists/youtube.txt", category: "tracking", description: "YouTube blocking. Blocks YouTube services (may affect Google services).", recommended: false, aggressiveness: 5, domain_count: 24280 },
    { name: "DeveloperDan AMP", url: "https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt", category: "tracking", description: "Google AMP blocking. Blocks AMP tracking and redirects.", recommended: false, aggressiveness: 3, domain_count: 16224 },
    { name: "DeveloperDan Facebook", url: "https://www.github.developerdan.com/hosts/lists/facebook-extended.txt", category: "tracking", description: "Extended Facebook blocking. Blocks FB tracking across the web.", recommended: false, aggressiveness: 4, domain_count: 29354 },
    { name: "EasyPrivacy Official", url: "https://easylist.to/easylist/easyprivacy.txt", category: "tracking", description: "Official EasyPrivacy (Adblock syntax). For AdGuard Home/uBlock.", recommended: false, aggressiveness: 3, domain_count: 18 },
    { name: "FadeMind 2o7Net", url: "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts", category: "tracking", description: "Omniture/Adobe Analytics trackers. Targets Adobe analytics specifically.", recommended: false, aggressiveness: 3, domain_count: 2014 },
    { name: "Frogeye Multi-Party Trackers", url: "https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt", category: "tracking", description: "Cross-site tracking domains. More aggressive than first-party list. May break some sites.", recommended: false, aggressiveness: 5, domain_count: 41507 },
    { name: "HKamran SmartTV", url: "https://raw.githubusercontent.com/hkamran80/blocklists/main/smart-tv.txt", category: "tracking", description: "Additional smart TV blocking. Complements other smart TV lists.", recommended: false, aggressiveness: 3, domain_count: 289 },
    { name: "Hagezi Apple Telemetry", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.apple.txt", category: "tracking", description: "Apple/iOS telemetry. Blocks Apple analytics and tracking.", recommended: false, aggressiveness: 3, domain_count: 105 },
    { name: "Hagezi Huawei Telemetry", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.huawei.txt", category: "tracking", description: "Huawei telemetry. For Huawei device privacy.", recommended: false, aggressiveness: 3, domain_count: 151 },
    { name: "Hagezi LG WebOS", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.lgwebos.txt", category: "tracking", description: "LG WebOS telemetry and ads. For LG smart TVs.", recommended: false, aggressiveness: 3, domain_count: 1704 },
    { name: "Hagezi Samsung Telemetry", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.samsung.txt", category: "tracking", description: "Samsung mobile telemetry. For Samsung device privacy.", recommended: false, aggressiveness: 3, domain_count: 270 },
    { name: "Hagezi TikTok", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.tiktok.txt", category: "tracking", description: "TikTok telemetry. Blocks TikTok tracking without fully blocking the service.", recommended: false, aggressiveness: 4, domain_count: 374 },
    { name: "Hagezi Xiaomi Telemetry", url: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.xiaomi.txt", category: "tracking", description: "Xiaomi telemetry. Essential for Xiaomi device privacy.", recommended: false, aggressiveness: 3, domain_count: 459 },
    { name: "No Amazon", url: "https://raw.githubusercontent.com/nickspaargaren/no-amazon/master/amazon.txt", category: "tracking", description: "Amazon services blocking. For reducing Amazon tracking.", recommended: false, aggressiveness: 4, domain_count: 3241 },
    { name: "No Google", url: "https://raw.githubusercontent.com/nickspaargaren/no-google/master/pihole-google.txt", category: "tracking", description: "Google services blocking. For degoogling your network.", recommended: false, aggressiveness: 5, domain_count: 6177 },
    { name: "NoTrack", url: "https://gitlab.com/quidsup/notrack-blocklists/-/raw/master/notrack-blocklist.txt", category: "tracking", description: "NoTrack project blocklist. Privacy-focused, well-maintained.", recommended: false, aggressiveness: 3, domain_count: 15564 },
    { name: "Perflyst Amazon FireTV", url: "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt", category: "tracking", description: "Fire TV specific trackers and ads. Complements SmartTV list.", recommended: false, aggressiveness: 3, domain_count: 16 },
    { name: "Prigent Ads", url: "https://v.firebog.net/hosts/Prigent-Ads.txt", category: "tracking", description: "French university tracker list. Academic research-backed tracking protection.", recommended: false, aggressiveness: 3, domain_count: 4227 },
    { name: "Samsung TV Telemetry", url: "https://raw.githubusercontent.com/mboutolleau/block-samsung-tv-telemetry/refs/heads/master/samsung_tv_telemetry_urls.txt", category: "tracking", description: "Samsung TV specific. Focused Samsung telemetry blocking.", recommended: false, aggressiveness: 3, domain_count: 28 },
    { name: "ph00lt0 Blocklist", url: "https://raw.githubusercontent.com/ph00lt0/blocklist/master/blocklist.txt", category: "tracking", description: "Independent research blocklist. Complements Hagezi+OISD. May affect Facebook, TikTok, Alexa, link shorteners.", recommended: false, aggressiveness: 4, domain_count: 212 }
];

// Check if collection is already populated to avoid overwriting existing user data
if (db.blocklist_library.countDocuments({}) === 0) {
    var formattedDocs = rawLists.map(function(list) {
        list.added_by = "system";
        list.created_at = new Date();
        list.updated_at = new Date();
        return list;
    });

    db.blocklist_library.insertMany(formattedDocs);
    print("Successfully seeded database with default Blocklist Library.");
} else {
    print("Blocklist Library already populated. Skipping seed.");
}
